# Generated by Django 5.1.1 on 2024-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grado_id',
            field=models.ManyToManyField(blank=True, to='notas.grados', verbose_name='ID grado Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
